# Generated by Django 3.2.5 on 2021-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default_course_image.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
